import { test, expect } from 'playwright/test'
import { PrismaClient } from '@prisma/client'
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3'
import { resolve } from 'node:path'

const db = new PrismaClient({ adapter: new PrismaBetterSqlite3({ url: `file:${resolve('workshop.db').replaceAll('\\', '/')}` }) })
test.afterAll(async () => { await db.$disconnect() })

test('zdrowy zakup: katalog → koszyk gościa → sesja → dostawa → płatność → zamówienie', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await expect(page.getByRole('link', { name: 'ShopEasy' })).toBeVisible()
  await expect(page.locator('[data-nextjs-dialog]')).toHaveCount(0)
  await page.screenshot({ path: '.workshop/browser-home.png', fullPage: true })
  await page.goto('/products/sluchawki-soundmax-x3')
  await expect(page.getByRole('heading', { name: 'Słuchawki bezprzewodowe SoundMax X3' })).toBeVisible()
  await page.getByRole('button', { name: /Dodaj do koszyka/ }).click()
  await page.goto('/cart')
  await expect(page.getByRole('heading', { name: /Koszyk \(1 szt\.\)/ })).toBeVisible()
  await page.getByRole('link', { name: 'Przejdź do kasy' }).click()
  await expect(page).toHaveURL(/\/login\?next=/)
  await page.getByLabel('E-mail', { exact: true }).fill('test@shopeasy.pl')
  await page.getByLabel('Hasło', { exact: true }).fill('Test1234!')
  await page.getByRole('button', { name: 'Zaloguj się', exact: true }).click()
  await expect(page).toHaveURL(/\/checkout\/delivery/)
  await expect.poll(async () => (await db.cartItem.findMany({ where: { userId: 'user-workshop' } })).length).toBe(1)
  const cookie = (await context.cookies()).find((value) => value.name === 'shopeasy_session')
  expect(cookie?.httpOnly).toBe(true)
  await page.getByLabel('Imię', { exact: true }).fill('Jan')
  await page.getByLabel('Nazwisko', { exact: true }).fill('Testowy')
  await page.getByLabel('Ulica i numer').fill('Testowa 12')
  await page.getByLabel('Kod pocztowy').fill('00-001')
  await page.getByLabel('Miasto').fill('Warszawa')
  await page.getByLabel('Telefon').fill('600000000')
  await page.getByRole('button', { name: 'Przejdź do płatności' }).click()
  await expect(page).toHaveURL(/\/checkout\/payment/)
  await expect(page.getByText('314,98', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'BLIK', exact: true }).click()
  await page.getByLabel('Kod BLIK').fill('123456')
  await page.getByRole('button', { name: 'Zapłać', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Zamówienie złożone!' })).toBeVisible()
  const orderId = new URL(page.url()).searchParams.get('orderId')!
  const order = await db.order.findUniqueOrThrow({ where: { id: orderId }, include: { items: true, statusHistory: true } })
  expect(order.total).toBe(31498)
  expect(order.deliveryCost).toBe(1499)
  expect(order.subtotal).toBe(29999)
  expect(order.paymentStatus).toBe('PAID')
  expect(order.items[0].productName).toBe('Słuchawki bezprzewodowe SoundMax X3')
  expect(order.statusHistory[0].status).toBe('ACCEPTED')
  expect(await db.cartItem.count()).toBe(0)
  await page.goto('/debug/emails')
  await expect(page.getByText(/Potwierdzenie zamówienia/)).toBeVisible()
  await page.goto('/account/orders')
  await expect(page.getByText('314,98', { exact: false })).toBeVisible()
  await page.screenshot({ path: '.workshop/browser-orders.png', fullPage: true })
  expect(errors).toEqual([])
})

test('API odrzuca ręcznie wpisaną tożsamość i reset usuwa stan przeglądarki', async ({ page, context, request }) => {
  const invalid = await request.post('/api/auth/login', { data: { email: 'test@shopeasy.pl', password: 'Wrong1234!' } })
  expect(invalid.status()).toBe(401)
  await context.addCookies([{ name: 'shopeasy_session', value: JSON.stringify({ user: { id: 'user-workshop', email: 'test@shopeasy.pl', name: 'Forgery' }, expiresAt: Date.now() + 60000 }), url: 'http://127.0.0.1:3100' }])
  await page.goto('/account/orders')
  await expect(page).toHaveURL(/\/login/)
  const session = await context.request.get('/api/auth/session')
  expect((await session.json()).user).toBeNull()
  await page.evaluate(() => {
    localStorage.setItem('shopeasy-guest-cart', JSON.stringify({ state: { items: [] }, version: 0 }))
    sessionStorage.setItem('checkout_delivery', 'fixture-old-delivery')
  })
  await page.goto('/workshop/reset')
  await page.getByRole('button', { name: 'Wyczyść stan przeglądarki' }).click()
  await expect(page.getByRole('status')).toContainText('Przeglądarka i wiadomości zresetowane')
  expect(await page.evaluate(() => localStorage.getItem('shopeasy-guest-cart'))).toBeNull()
  expect(await page.evaluate(() => sessionStorage.getItem('checkout_delivery'))).toBeNull()
  expect((await context.cookies()).some((value) => value.name === 'shopeasy_session')).toBe(false)
  await page.goto('/debug/emails')
  await expect(page.getByText('0 wiadomości')).toBeVisible()
  expect((await request.post('/api/workshop/browser-reset', { headers: { origin: 'http://example.invalid' } })).status()).toBe(403)
})
